version: '3.1'

volumes:
  data_dcateditor:
  data_dcatgenerator:

services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=- --server=127.0.0.11 --server=193.10.57.11 --server=8.8.8.8 --server=172.16.0.72 --server=172.16.0.7 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600 --all-servers
    cap_add: 
      - NET_ADMIN 
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:dcateditor.bioatlas.se
      - proxy:dcatgenerator.bioatlas.se

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  generator:
    image: bioatlas/dcatapgenerator:latest
    environment:
      - VIRTUAL_HOST=dcatgenerator.bioatlas.se
      - VIRTUAL_PORT=4000

  editor:
    image: bioatlas/dcatapeditor:latest
    environment:
      - VIRTUAL_HOST=dcateditor.bioatlas.se
      - VIRTUAL_PORT=4000

