---
basic:
  - name: Title
    definition: Human-readable name
    json: title
    rdfa: dct:title

  - name: Description
    definition: Human-readable description
    json: description
    rdfa: dct:description

  - name: Tags
    definition: Keywords describing tags
    json: keyword
    rdfa: dcat:keyword
    type: text

  - name: Last Update
    definition: Most recent date modified
    json: modified
    rdfa: dct:modified

  - name: Publisher
    definition: The publishing agency
    json: publisher
    rdfa: dct:publisher

  - name: Contact Name
    definition: "[First] [Last]"
    json: contactPoint
    rdfa: dcat:conctactPoint

  - name: Contact Email
    definition: Contact person's email
    json: mbox
    rdfa: foaf:mbox

  - name: Unique Identifier
    definition: A unique identifier for the dataset
    json: identifier
    rdfa: dct:identifier

  - name: Public Access Level
    definition: "'public', 'restricted public' or 'non-public'"
    json: accessLevel

  - name: Access Level Comment
    definition: explanation for the selected “accessLevel”
    json: accessLevelComment

  - name: Bureau Code
    definition:  "Combined agency and bureau code in format XXX:XX"
    json: bureauCode

  - name: Program Code
    definition:  The primary program related to this data asset in format XXX:XXX
    json: programCode

  - name: Download URL
    definition: URL to dataset 
    json: accessURL
    rdfa: dcat:accessURL
    type: url

  - name: Endpoint
    definition: API Endpoint
    json: webService
    type: url

  - name: Format
    definition: File format or API type
    json: format
    rdfa: dct:format

  - name: License
    definition: The license dataset is published with
    json: license
    rdfa: dct:license

  - name: Spatial
    definition: Range of spatial applicability
    json: spatial
    rdfa: dct:spatial

  - name: Temporal
    definition: Range of temporal applicability
    json: temporal
    rdfa: dct:temporal

expanded:

  - name: Category
    definition: Main thematic category
    json: theme
    rdfa: dcat:theme

  - name: Data Dictionary URL
    definition: URL to the data dictionary for the dataset or API
    json: dataDictionary
    type: url

  - name: Data Quality
    definition: Whether the dataset meets the agency's Information Quality Guidelines (true/false)
    json: dataQuality

  - name: Distribution
    definition:  Multiple download URLs for datasets composed of multiple files
    json: distribution

  - name: Frequency
    definition: Frequency of update
    json: accrualPeriodicity
    rdfa: dct:accrualPeriodocity

  - name: Homepage URL
    definition: Dataset homepage
    json: landingPage
    rdfa: dcat:landingPage
    type: url

  - name: Language
    definition: Language of the dataset
    json: language
    rdfa: dct:language

  - name: Primary IT Investment UII
    definition: For linking a dataset with an IT Unique Investment Identifier (UII)
    json: PrimaryITInvestmentUII

  - name: Related Documents
    definition: Related material
    json: references

  - name: Release Date
    definition: Date of formal issuance.
    json: issued
    rdfa: dct:issued

  - name: System of Records
    definition: URL to the System of Records for this dataset
    json: systemOfRecords
    type: url
